export default {
  "chemistry": "化学",
  "changes": "变化",
  "properties": "性质",
  "elements": "元素 · 🚧",
  "allotrope": "同素异形体",
  "amorphous-carbon": "无定形碳",
  "combustion": "燃烧",
  "flammability": "可燃性",
  "combustibles": "可燃物",
  "dispersion": "分散系",
  "solution": "溶液",
  "solute": "溶质",
  "solvent": "溶剂",
  "acidity": "酸碱性",
  "colloid": "胶体",
  "semipermeable-membrane": "半透膜",
  "ph":"pH 值",
  "turbid-liquid": "浊液 · 🚧",
  "electrolyte": "电解质 · 🚧"
}